# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: course.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'course.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ourse.proto\x12\x06\x63ourse\"\x1b\n\rCourseRequest\x12\n\n\x02id\x18\x01 \x01(\t\"@\n\x0e\x43ourseResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\"7\n\x11\x45nrollmentRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x11\n\tcourse_id\x18\x02 \x01(\t\"%\n\x12\x45nrollmentResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\x90\x01\n\rCourseService\x12:\n\tGetCourse\x12\x15.course.CourseRequest\x1a\x16.course.CourseResponse\x12\x43\n\nEnrollUser\x12\x19.course.EnrollmentRequest\x1a\x1a.course.EnrollmentResponseB\x10Z\x0eproto/coursepbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'course_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\016proto/coursepb'
  _globals['_COURSEREQUEST']._serialized_start=24
  _globals['_COURSEREQUEST']._serialized_end=51
  _globals['_COURSERESPONSE']._serialized_start=53
  _globals['_COURSERESPONSE']._serialized_end=117
  _globals['_ENROLLMENTREQUEST']._serialized_start=119
  _globals['_ENROLLMENTREQUEST']._serialized_end=174
  _globals['_ENROLLMENTRESPONSE']._serialized_start=176
  _globals['_ENROLLMENTRESPONSE']._serialized_end=213
  _globals['_COURSESERVICE']._serialized_start=216
  _globals['_COURSESERVICE']._serialized_end=360
# @@protoc_insertion_point(module_scope)
